version: '3.8'

services:
  mapandreducesocket:
    container_name: map-and-reduce-socket
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

networks:
  default:
      name: srvnecmettin